spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:document}?currentSchema=${PG_SCHEMA:public}
    username: ${PG_USER:docs}
    password: ${PG_PASS:pass}
    pool:
      max-size: 10
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:document}?currentSchema=${PG_SCHEMA:public}
    user: ${PG_USER:docs}
    password: ${PG_PASS:pass}

app:
  worker:
    enabled: ${WORKERS_ENABLED:true}
    approve:
      batchSize: ${WORKERS_APPROVE_BATCH_SIZE:10}
      delay: ${WORKERS_APPROVE_DELAY:PT50S}
    submit:
      batchSize: ${WORKERS_SUBMIT_BATCH_SIZE:10}
      delay: ${WORKERS_SUBMIT_DELAY:PT50S}