spring:
  main:
    banner-mode: off
  r2dbc:
    name: docs
    url: r2dbc:postgresql://localhost:5432/document?currentSchema=public
    username: docs
    password: pass
    pool:
      max-size: 10
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    url: jdbc:postgresql://localhost:5432/document?currentSchema=public
    user: docs
    password: pass

app:
  worker:
    enabled: true
    approve:
      batchSize: 10
      delay: PT50S
    submit:
      batchSize: 10
      delay: PT50S